### ISSUE TITLE
please make a linux executable app that patchs the exe of efootball, so i can play the game with proton on 165 fps smoothly

### ISSUE THREAD

**Issue by EliN4til** [CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher#2]

**Comment by CadiLillian** [comment]
As eFootball is not officially supported (available) for Linux, I will not make a Linux specific version.
You should be able to use a software like [Wine HQ](https://www.winehq.org/), which allows you to run Windows executables on Linux, to run the patcher on Linux.
