### ISSUE TITLE
I know you didn't support linux because efootball only for windows, but can you update so it can select the executable path manually?

### ISSUE THREAD

**Issue by Moanrisy** [CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher#6]
![cant-find-path](https://github.com/CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher/assets/17421945/84c62660-fdc6-44af-a32e-a31a67f3c3d5)

Successfully run the patcher but I'm not sure how to set the correct path.

**Comment by CadiLillian** [comment]
Hi, please try running the patcher in the same directory as your eFootball executable.
If this doesn't work and the file type is not .exe, try changing the file type of the eFootball executable to .exe and test the patcher.
You can change it back afterwards.

**Comment by Moanrisy** [comment]
![image](https://github.com/CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher/assets/17421945/9e9d4171-ec30-45e0-8af0-08eb62e7fd38)

Oh it's working, thank you very much.
