### ISSUE TITLE
Program Closes Automatically on Microsoft Store Version

### ISSUE THREAD

**Issue by xDaymal** [CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher#8]
I am experiencing an issue with your program. When I open the version downloaded from the Microsoft Store, it automatically closes immediately after launching. I’ve tried multiple times, but the issue persists. However, the Steam version works perfectly without any problems.

Could you help me understand what might be causing this malfunction? Is there a specific setting or update I need for the Microsoft Store version?

Thank you in advance for your assistance. I am available to provide any additional details if needed.

**Comment by CadiLillian** [comment]
Please read this [post](https://evoweb.uk/threads/efootball-fps-limit-and-vsync-patcher.93599/post-4115904) in the official evoweb thread of the eFootball FPS Limit and VSync Patcher.
Try it and use the latest version of the patcher.
I will update the setup instructions for the MS Store version if it works for you.

**Comment by xDaymal** [comment]
It worked thank you so much :)
