### ISSUE TITLE
Stuttering on goal

### ISSUE THREAD

**Issue by darceyo** [CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher#9]
When I scoring a goal, I **always** have the micro stutter! how to fix that!? It is just pisses me off...
I'm playing at 120 FPS, but also tried 100, 90 and 80 too.
https://www.youtube.com/watch?v=4kLiODfOu-w

I would be grateful for a response!

**Comment by CadiLillian** [comment]
This has nothing to do with the patcher.
Please keep the issues in this repo strictly patcher-related!

You can thank KONAMI for their terrible optimisation, or rather non-existent optimisation.
